USE [dw]
GO

CREATE UNIQUE NONCLUSTERED INDEX [NK_REPLACE_VALUE_DIM_TABLE_NAME] ON [dbo].[REPLACE_VALUE_DIM_TABLE_NAME]
(
	[gl_string] ASC,
	[is_current] ASC
)
WHERE ([is_current]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
