USE [dw]
GO

ALTER TABLE [dbo].[REPLACE_VALUE_FACT_TABLE_NAME]  WITH CHECK ADD  CONSTRAINT [FK_REPLACE_VALUE_FACT_TABLE_NAME_REPLACE_VALUE_DIM_TABLE_NAME] FOREIGN KEY([table_key])
REFERENCES [dbo].[DIM_TABLE_NAME] ([dim_key])
GO

ALTER TABLE [dbo].[REPLACE_VALUE_FACT_TABLE_NAME] CHECK CONSTRAINT [FK_REPLACE_VALUE_FACT_TABLE_NAME_REPLACE_VALUE_DIM_TABLE_NAME]
GO