USE stg_dw
GO

CREATE PROCEDURE AS {REPLACE_VALUE_SCHEMA_NAME}.usp_merge_{REPLACE_VALUE_TABLE_NAME}
AS
MERGE INTO {REPLACE_VALUE_SCHEMA_NAME}.{REPLACE_VALUE_TABLE_NAME} tgt
USING {REPLACE_VALUE_SCHEMA_NAME}.{REPLACE_VALUE_TABLE_NAME}_intermediate src
	ON src.{REPLACE_VALUE_PRIMARY_KEY} = tgt.{REPLACE_VALUE_PRIMARY_KEY}
WHEN MATCHED THEN UPDATE SET
	tgt.column1 = src.column1
	,tgt.column2 = src.column2
WHEN NOT MATCHED THEN INSERT (
	column1
	,column2
	) VALUES (
	src.column1
	,src.column2
	);